stages:
  - validate
  - deploy
  - verify

variables:
  MASTER_IP: ""
  SSH_KEY_NAME: "ds_exam_key"
  KUBERNETES_DIR: "kubernetes"
  REMOTE_DIR: "wordpress"
  WORDPRESS_PORT: "30080"  # Updated to use the NodePort for ingress

validate:
  stage: validate
  image: alpine:latest
  script:
    - echo "Validating Kubernetes manifests..."
    - echo "Using basic YAML validation instead of kubectl dry-run"
    - apk add --no-cache grep
    - for file in $KUBERNETES_DIR/*.yaml; do
        echo "Checking $file";
        grep -q "apiVersion:" $file || (echo "Missing apiVersion in $file" && exit 1);
        grep -q "kind:" $file || (echo "Missing kind in $file" && exit 1);
      done
    - echo "All Kubernetes manifests are valid!"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "development"

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/$SSH_KEY_NAME.pem
    - chmod 600 ~/.ssh/$SSH_KEY_NAME.pem
    - echo -e "Host $MASTER_IP\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

    
    
    - ls -la ~/.ssh/
    - head -n 1 ~/.ssh/$SSH_KEY_NAME.pem 

  script:
    - echo "Creating remote directory..."
    - ssh -i ~/.ssh/$SSH_KEY_NAME.pem ubuntu@$MASTER_IP "mkdir -p ~/$REMOTE_DIR"
    
    - echo "Transferring Kubernetes manifests..."
    - scp -i ~/.ssh/$SSH_KEY_NAME.pem $KUBERNETES_DIR/*.yaml ubuntu@$MASTER_IP:~/$REMOTE_DIR/
    
    - echo "Applying Kubernetes manifests..."
    - ssh -i ~/.ssh/$SSH_KEY_NAME.pem ubuntu@$MASTER_IP "cd ~/$REMOTE_DIR && \
        sudo kubectl apply -f namespace.yaml && \
        sudo kubectl apply -f s3-secret.yaml && \
        sudo kubectl apply -f wordpress-pvc.yaml && \
        sudo kubectl apply -f mysql-deployment.yaml && \
        sudo kubectl apply -f wordpress-deployment.yaml && \
        sudo kubectl apply -f wordpress-service.yaml && \
        sudo kubectl apply -f wordpress-loadbalancer.yaml && \
        sudo kubectl apply -f wordpress-ingress.yaml"
    
    - echo "WordPress deployment completed successfully!"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "development"
  environment:
    name: production
    url: http://$MASTER_IP:$WORDPRESS_PORT

verify:
  stage: verify
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client curl bash
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/$SSH_KEY_NAME.pem
    - chmod 600 ~/.ssh/$SSH_KEY_NAME.pem
    - echo -e "Host $MASTER_IP\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - echo "Verifying deployment status..."
    - ssh -i ~/.ssh/$SSH_KEY_NAME.pem ubuntu@$MASTER_IP "sudo kubectl get all -n wordpress"
    - ssh -i ~/.ssh/$SSH_KEY_NAME.pem ubuntu@$MASTER_IP "sudo kubectl get ingress -n wordpress"
    
    - echo "Checking WordPress availability via LoadBalancer..."
    - ssh -i ~/.ssh/$SSH_KEY_NAME.pem ubuntu@$MASTER_IP "curl -s --retry 5 --retry-delay 10 -o /dev/null -w \"%{http_code}\" http://localhost:32412" | grep -q 200
    
    - echo "Checking WordPress availability via Ingress..."
    - ssh -i ~/.ssh/$SSH_KEY_NAME.pem ubuntu@$MASTER_IP "curl -s --retry 5 --retry-delay 10 -o /dev/null -w \"%{http_code}\" http://localhost:30080" | grep -q 200
    
    - echo "Verification completed successfully!"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "development"
