apiVersion: v1
kind: Service
metadata:
  name: prometheus-service # Internal service for Grafana
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP # Only expose internally initially
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport # Optional: Service for external access via NodePort
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30900 # Expose Prometheus on NodePort 30900
  type: NodePort