apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: wordpress-${ENVIRONMENT}
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:5.7
            command:
            - /bin/bash
            - -c
            - |
              mysqldump -h wordpress-mysql -u wordpress -p$MYSQL_PASSWORD wordpress | gzip > /backup/wordpress-db-$(date +%Y%m%d).sql.gz
              aws s3 cp /backup/wordpress-db-$(date +%Y%m%d).sql.gz s3://$S3_BUCKET/backups/databases/
            env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: S3_BUCKET
              value: "ds-exam-app-data-xotjx8lp"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret-key
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            emptyDir: {}
          restartPolicy: OnFailure