apiVersion: v1
kind: Service
metadata:
  name: wordpress-lb
  namespace: wordpress
spec:
  selector:
    app: wordpress
    # Remove tier: frontend since your pods don't have this label
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
