apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-tls
  namespace: wordpress
spec:
  dnsNames:
  - MASTER_IP.nip.io  # Will be replaced during deployment
  secretName: wordpress-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
