# Environment-specific variables
.dev_environment: &dev_environment
  variables:
    ENVIRONMENT: "dev"
    TF_VAR_FILE: "environments/dev/terraform.tfvars"
    REPLICA_COUNT: "1"
    MEMORY_REQUEST: "256Mi"
    MEMORY_LIMIT: "512Mi"
    CPU_REQUEST: "200m"
    CPU_LIMIT: "500m"
    CERT_ISSUER: "staging"
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

# Production Environment
.prod_environment: &prod_environment
  variables:
    ENVIRONMENT: "prod"
    TF_VAR_FILE: "environments/prod/terraform.tfvars"
    REPLICA_COUNT: "2"
    MEMORY_REQUEST: "512Mi"
    MEMORY_LIMIT: "1Gi"
    CPU_REQUEST: "500m"
    CPU_LIMIT: "1000m"
    CERT_ISSUER: "prod"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"